### ISSUE TITLE
Instructions for GPU acceleration in Fiji on Windows are incomplete

### ISSUE THREAD

**Issue by nicost** [mpicbg-csbd/CSBDeep#13]
Trying to get GPU acceleration in Fiji on Windows to work, and following the instructions on https://github.com/CSBDeep/CSBDeep_website/wiki/CSBDeep-in-Fiji-%E2%80%93-Installation.  That page says to install the NVidia requirements as described in the Tensorflow Documentation, which links to: https://www.tensorflow.org/install/gpu.  That page says to install CUDA 10.0.  

Only after much more digging one can discover that does not work, and one needs to install CUDA 9 and cuDNN 7 to work with tensorflow 1.12 (which apparently is the Tensorflow version currently distributed from CBSDeep-Tensorflow).  It would be super helpful to list the exact requirements directly on the CBSDeep Installation page.

**Comment by frauzufall** [comment]
Hi @nicost , you are absolutely right, sorry, it also took me a while to understand the version compatibility mess.

Could you have a look at the [updated wiki site](https://github.com/CSBDeep/CSBDeep_website/wiki/CSBDeep-in-Fiji-%E2%80%93-Installation#gpu-support)? I tried to be more specific. 

We also now have a plugin which should make it easier to switch to a different TensorFlow version matching your system, so if you have CUDA 10 installed, you can open `Edit > Options > TensorFlow...` and switch to TensorFlow 1.13 or 1.14. Let me know if you are experiencing any additional issues or if the documentation is still not sufficient.

**Comment by nicost** [comment]
@frauzufall: Thanks!  Now got it working (on a Windows 7 machine).  Failed to get it to go on Windows 10, but will look in detail later.  There are so many moving parts here that this extra information is very useful.  Switching between GPU and CPU versions also works nicely.  Thanks!

**Comment by frauzufall** [comment]
Great! Please let me know if the reason for failure on Windows 10 related to CSBDeep / the new `imagej-tensorflow` library management tool.
