### ISSUE TITLE
sample length scales vs. training voxel size

### ISSUE THREAD

**Issue by erjel** [mpicbg-csbd/CSBDeep#5]
Hi,

I have read your biorxiv [preprint](https://www.biorxiv.org/content/early/2017/12/21/236463) with great interest and started to test the described network architecture on my own.
Are the presented images (i.e. Sup. Fig. 1 A ) directly extracted from the training/ validation batches? How large are the batches (64x64x16 px) compared to the characteristic biological sample features (i.e. cell length)?

Thanks,
Eric

**Comment by tboo** [comment]
Hi Eric,

The data from Figure S1A is indeed validation data. However the crops we show in Fig S1A do not correspond to the batch size (or crop) we used for training. The training for denoising planarian data was done in 3 dimensions (64x64x16 voxels). The validation itself (FigS1A) was done in 2D (200x200 pixels).  

The feature (nuclei) size for planaria is in our case approximately 10-15 pixels in diameter.

I hope that gives you an idea how to chose the batch size for your features.

Cheers,

Tobias
